import MainHeader from "@/components/main-header";
import "./globals.css";

export const metadata = {
  title: "Create Portfolio Web Site",
  description: "Generated by create portfolio web site",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
